services:
  app1:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - INSTANCE_ID=Instance_1
    volumes:
      - ./templates:/app/templates
    depends_on:
      - redis
    container_name: app1

  app2:
    build:
      context: .
    ports:
      - "5001:5000"
    environment:
      - INSTANCE_ID=Instance_2
    volumes:
      - ./templates:/app/templates
    depends_on:
      - redis
    container_name: app2

  app3:
    build:
      context: .
    ports:
      - "5002:5000"
    environment:
      - INSTANCE_ID=Instance_3
    volumes:
      - ./templates:/app/templates
    depends_on:
      - redis
    container_name: app3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
    container_name: nginx

  redis:
    image: redis:latest
    container_name: redis